resolver: lts-5.6
packages:
- '.'
extra-deps:
- names-th-0.2.0.1
- persistable-record-0.4.0.0
- relational-query-0.8.1.0
- sql-words-0.1.3.1
flags:
  persistent-relational-record:
    test-examples: True
extra-package-dbs: []
