resolver: lts-5.1
packages:
- '.'
extra-deps:
- HDBC-session-0.1.0.0
- names-th-0.2.0.1
- persistable-record-0.3.0.0
- relational-query-0.8.0.4
- relational-query-HDBC-0.5.0.0
- relational-schemas-0.1.2.2
- sql-words-0.1.3.1
flags: {}
extra-package-dbs: []
