resolver: lts-5.1
packages:
- location:
    git: https://github.com/khibino/haskell-relational-record.git
    commit: master
  subdirs:
    - names-th
    - persistable-record
    - relational-query
    - sql-words
- '.'
extra-deps:
- quickcheck-simple-0.1.0.0
flags: {}
extra-package-dbs: []
