resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/khibino/haskell-relational-record.git
    commit: master
  subdirs:
    - names-th
    - persistable-record
    - relational-query
    - sql-words
extra-deps: []
flags:
  persistent-relational-record:
    test-examples: True
extra-package-dbs: []
