name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.6.5', '8.8.4', '8.10.7' ]
        cabal: [ '3.2' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-cabal-store-cabal${{ matrix.cabal }}-ghc${{ matrix.ghc }}

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build all --only-dependencies --enable-tests
    - name: Build
      run: cabal v2-build all
    - name: Run tests
      run: cabal v2-test all

  hlint:
    name: lint *.hs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install hlint
        run: sudo apt-get install hlint

      - run: hlint --git

  cabal-format:
    name: check .cabal style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1
        with:
          cabal-version: '3.2'
      - run: cabal format
      - run: git diff --exit-code
